### ISSUE TITLE
Load screen version number needs to be changed (from 0.5.3) for 0.6.0

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Assets-Masters#12]
The load screen shows a version number. This should be updated before we release the 0.6.0 branch.

**Comment by evertvorster** [comment]
The version number is now not shown at all, rendering this point moot. Let's close this issue and move on to more fun stuff.

**Comment by BenjamenMeyer** [comment]
https://github.com/vegastrike/Assets-Production/pull/6 resolves this in Assets Production.

@evertvorster do we need to fix this in Assets-Masters too?

**Comment by pyramid3d** [comment]
The master file (https://github.com/vegastrike/Assets-Masters/blob/master/sprites/interfaces/main_menu/sources/menu-main.xcf) contains the version number as a layer which can be enabled/disabled. SO there is no need to change the master file.
