### ISSUE TITLE
Desktop/Launcher/Icon for vsettings

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Assets-Masters#20]
We need an icon on the desktop that launches the `vsettings` script (vegasettings program), just like we have one for the `vs` script that runs the vsUTCS game itself. The two icons can probably share the same V|S logo, I'm thinking.

**Comment by BenjamenMeyer** [comment]
Made it part of 0.9.x; if we get it in sooner great, but we'll require it for 0.9.x.

**Comment by stephengtuggy** [comment]
So this feature is done as of 0.7.x. (Thanks, @evertvorster !) Now it just needs to be merged into 0.8.x and master.

**Comment by BenjamenMeyer** [comment]
@stephengtuggy @evertvorster  was it only against the 0.7.x branch?

**Comment by stephengtuggy** [comment]
@BenjamenMeyer @evertvorster Never mind. I just checked, and these files are already on the 0.8.x and master branches. My mistake.

So this ticket can be closed completely, then.

**Comment by BenjamenMeyer** [comment]
@stephengtuggy cool; thanks for checking.
