### ISSUE TITLE
Update install instructions with reference to vs and vsettings, plus new vsettings icon

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Assets-Masters#23]
Tell users (especially those who have played Vega Strike before) the following:

- To run Vega Strike from the command line, the recommended approach currently is to run the `vs` script from the data directory, `/usr/share/vegastrike`. The `vegastrike` engine binary will then know automagically where to find the data / assets.
- Instead of vssetup, run the `vsettings` script, again from the `/usr/share/vegastrike` data directory. Behind the scenes, this runs the `vegasettings` binary, which replaces `vssetup`.
- There should be a desktop/menu icon for vsettings, as well as one for vs, that "just works."

**Comment by BenjamenMeyer** [comment]
@stephengtuggy https://github.com/vegastrike/Vega-Strike-Engine-Source/pull/440 satisfies this for 0.7.x; we can forward port that to master for 0.8.x.

**Comment by BenjamenMeyer** [comment]
With #440 merged, we just need to port it to master.

**Comment by stephengtuggy** [comment]
This documentation update needs to be applied to master as well.
