### ISSUE TITLE
Release tar ball missing programs

### ISSUE THREAD

**Issue by susnux** [vegastrike/Assets-Masters#29]
**Describe the bug**
The programs directory is missing in the tar.xz release tar ball.
( `vsUTCS_v0.7.0-Source.tar.xz` )

**Comment by stephengtuggy** [comment]
@susnux could you verify whether or not this problem is fixed as of https://github.com/vegastrike/Assets-Production/releases/tag/v0.7.1-beta1 ?

**Comment by BenjamenMeyer** [comment]
Added #31 to track the rename separately. This can be closed out once someone (preferably @susnux ) confirms that the latest releases fix this.

**Comment by pyramid3d** [comment]
As far as I recall, the programs directory was introduced by former contributor klauss during his planetary shader improvements stanza. https://github.com/vegastrike/Assets-Production/tree/master/programs seems to contain the shader programs but I do not have any insight as to how those tie into the code as those changes happened during my hiatus from the project. If you really need to track it back the old svn repo should still have the history available.

**Comment by susnux** [comment]
> @susnux could you verify whether or not this problem is fixed as of https://github.com/vegastrike/Assets-Production/releases/tag/v0.7.1-beta1 ?

It works as expected :+1:
