### ISSUE TITLE
Output of mission jumps list is off by one

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Assets-Masters#40]
If you are in System A, and you need to get to System E to complete your mission, then the output should be:

```
From System A
Jump to System B
Jump to System C
Jump to System D
Jump to System E
When you get to System E, patrol it
```

Instead, the output lists System A twice, and does not list the jump to System E at all. The output will be as follows:

```
From System A
Carefully go to the System A
Then jump to System B
Then jump to System C
Then jump to System D
You should shortly arrive in System E: patrol it
```

So "System A" is repeated twice, and "System E" is left off at the end of the `jump to` instructions.

If there are no objections, I'd like to fix this issue. I believe the relevant section of code is [this one](https://github.com/vegastrike/Assets-Production/blob/1756685a19286c5f9b070bcd0b7b3164e20466a5/modules/go_to_adjacent_systems.py#L59).

**Comment by stephengtuggy** [comment]
The same code is repeated in the same file in PWCU, so I'm pretty sure PWCU has the same bug.

**Comment by BenjamenMeyer** [comment]
@stephengtuggy please file a bug with PWCU pointing it out to and crosslink.

**Comment by stephengtuggy** [comment]
> 

@BenjamenMeyer Done.
