### ISSUE TITLE
weapons.json is not being installed

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Assets-Masters#43]
This is a new file, and it's not included in the CMakelists.txt

Without it, the game crashes hard on startup. 

Attached is a zipped file of the patch to get it to install. 

[weapons_fix.zip](https://github.com/vegastrike/Assets-Masters/files/8843016/weapons_fix.zip)

**Comment by stephengtuggy** [comment]
Does this change really need to be made in 0.8.x? Or just in 0.9.x/`master`?

**Comment by evertvorster** [comment]
If 0.8.x will ever get the engine interpreting json, then it needs it.

As far as I am aware that was not in the plans, and releases are only
supposed to get bug fixes?

Kind regards,
Evert Vorster
Awesome Chapters Tours
http://www.awesomechapters.com
Tel: +264 (0) 811477690

**Comment by BenjamenMeyer** [comment]
no, we're not back porting it to 0.8.x. 0.8.x is what is it; though we'll fix bugs there if they come up.
@evertvorster the Arch stuff only pulls master, right? The question came up b/c of a bug report from an Arch user IIRC.

**Comment by evertvorster** [comment]
There are four arch packages, a set of engine and assets that pull master,
and then a set that pulls the latest release.

But if the latest release will not get the json interpreting engine, then
it does not need the patch. In fact, I think the patch will break install
as it will look for a file that does not exist in that branch.

**Comment by stephengtuggy** [comment]
Can this issue be closed? I.e., is it fixed?

**Comment by stephengtuggy** [comment]
I'm closing this ticket. I'm quite certain that it is fixed.
