### ISSUE TITLE
Koala ship is missing from vessels.csv

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Assets-Masters#6]
in Dec 2013, the csv files were split. 
The Koala vessel was never transferred to the new vessels.csv file. 

This is causing "Unit file koala not found errors"

I have tried copying the Koala lines from units.csv to vessels.csv, but the formats are different.

**Comment by vincele** [comment]
duplicate of #11 ?

**Comment by evertvorster** [comment]
When we reverted the units.csv split, the Koala came back. Closing this issue
